name: '${COMPOSE_PROJECT_NAME}'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      MYSQL_DATABASE: '${WORDPRESS_DB_NAME}'
      MYSQL_USER: '${WORDPRESS_DB_USER}'
      MYSQL_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
    volumes:
      - "./.srv/database:/var/lib/mysql"

  wordpress:
    # Гнучке керування версіями через змінні
    image: wordpress:php${PHP_VERSION}-apache
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: 'mysql'
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_DISPLAY', true);
    volumes:
      # 1. Основні файли WordPress
      - './.srv/wordpress:/var/www/html'

      # 2. Твої плагіни з папки integrity
      - './integrity/plugins:/var/www/html/wp-content/plugins'

      # 3. Твої теми з папки integrity
      - './integrity/themes:/var/www/html/wp-content/themes'

      # 4. Налаштування PHP
      - './custom.ini:/usr/local/etc/php/conf.d/custom.ini'